#!/usr/bin/env bash

export CONTECO_LABEL="solution.blank -SolEco"
export CONTECO_DESCRIPTION="The SolEco blank solution."

export CONTECO_TYPE="solution"
export CONTECO_NAME="blank"
export CONTECO_TAG="v1.0.2"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="soleco"
